FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main

RUN dpkg --add-architecture arm64 && \
    apt-get update && \
    apt-get install -y \
        libwayland-dev:arm64 \
        libxcb1-dev:arm64 \
        libxcb-randr0-dev:arm64 \
        libxcb-shm0-dev:arm64 \
        libxcb-xfixes0-dev:arm64 \
        libxkbcommon-dev:arm64 \
        libdbus-1-dev:arm64 \
        libegl-dev:arm64 \
        libgl-dev:arm64 \
        libgbm-dev:arm64 \
        libvulkan-dev:arm64 \
        libpipewire-0.3-dev:arm64 \
    && rm -rf /var/lib/apt/lists/*
